DROP TABLE IF EXISTS SO_USER CASCADE;
CREATE TABLE SO_USER(
    USER_ID VARCHAR(50) PRIMARY KEY,
    EMAIL_ID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    DISPLAY_NAME VARCHAR(100),
    UNIQUE KEY (EMAIL_ID)
);